title = "Social Force Config File"

[scene]
enable_group = false
agent_radius = 0.35
step_width = 1.0
# the maximum speed doesn't exceed 1.3x initial speed
max_speed_multiplier = 1.3
tau = 0.5
resolution = 10

[goal_attractive_force]
factor = 1

[ped_repulsive_force]
factor = 1.5
v0 = 2.1
sigma = 0.3
# fov params
fov_phi = 100.0
fov_factor = 0.5 # out of view factor

[space_repulsive_force]
factor = 1
u0 = 10
r = 0.2

[desired_force]
factor = 1.0
# The relaxation distance of the goal
goal_threshold = 0.2
# How long the relaxation process would take
relaxation_time = 0.5


[social_force]
factor = 5.1
# Moussaid-Helbing 2009
# relative importance of position vs velocity vector
lambda_importance = 2.0
# define speed interaction
gamma = 0.35
n = 2
# define angular interaction
n_prime = 3

[obstacle_force]
factor = 0.5
#0.5 is better for us
# the standard deviation of obstacle force
sigma = 0.2
# threshold to trigger this force
threshold = 3.0

[group_coherence_force]
factor = 3.0

[group_repulsive_force]
factor = 1.0
# threshold to trigger this force
threshold = 0.55

[group_gaze_force]
factor = 4.0
# fielf of view
fov_phi = 90.0